apiVersion: v2
name: ocular-default-integrations
version: "0.2.0"
appVersion: "0.1.9"
kubeVersion: ">=1.26.0-0"
description: A Helm chart for deploying default ocular integrations
type: application
icon: "https://ocularproject.io/favicon-32x32.png"
home: https://ocularproject.io
sources:
  - https://github.com/crashappsec/ocular-default-integrations
maintainers:
  - name: Bryce Thuiot
    email: bryce@crashoverride.com
keywords:
  - git
  - kubernetes
  - scanning
  - sast
  - secrets
  - sca
  - security
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: GPL-3.0
