# configuration of crawlers
crawlers:
  secretName: "crawler-secrets"
  image:
    repository: "ghcr.io/crashappsec/ocular-default-crawlers"
    tag: "v{{ .Chart.AppVersion }}"

# configuration of downloaders
downloaders:
  secretName: "downloader-secrets"
  image:
    repository: "ghcr.io/crashappsec/ocular-default-downloaders"
    tag: "v{{ .Chart.AppVersion }}"

# Configuration for uploaders
uploaders:
  secretName: "uploader-secrets"
  image:
    repository: "ghcr.io/crashappsec/ocular-default-uploaders"
    tag: "v{{ .Chart.AppVersion }}"
