{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "chalkular.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "chalkular.resourceName" (dict "suffix" "chalkreportpolicy-viewer-role" "context" $) }}
rules:
- apiGroups:
  - chalk.ocular.crashoverride.run
  resources:
  - chalkreportpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chalk.ocular.crashoverride.run
  resources:
  - chalkreportpolicies/status
  verbs:
  - get
{{- end }}
