apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chalkular.resourceName" (dict "suffix" "report-uploader" "context" $) }}
rules:
- nonResourceURLs:
  - /api/v1beta1/report
  verbs:
  - post
