apiVersion: v2
name: chalk-operator
description: A Kubernetes operator that enriches chalk-annotated pods with cluster metadata
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - kubernetes
  - operator
  - metadata
  - enrichment
  - webhook
home: https://github.com/crashappsec/chalk-operator
sources:
  - https://github.com/crashappsec/chalk-operator
maintainers:
  - name: Crash Override
    email: info@crashoverride.run
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: GPL-3.0
