apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterDownloader
metadata:
  name: {{ include "chalkular.resourceName" (dict "suffix" "chalkmark-extract" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  container:
    env: []
    image: {{ .Values.downloader.image.repository }}:{{ .Values.downloader.image.tag }}
    imagePullPolicy: {{ .Values.downloader.image.pullPolicy }}
    name: chalkmark-extract
    volumeMounts: []
  metadataFiles:
  - chalk.json
  parameters:
  - default: ""
    description: Which platform to download for the image
    name: PLATFORM
  - default: ""
    description: If set to a non-empty value, registry connection uses http
    name: INSECURE_REGISTRY
  volumes: []
