{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: ocular
        control-plane: controller-manager
    name: ocular-controller-manager-metrics-service
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - name: https
          port: 8443
          protocol: TCP
          targetPort: 8443
    selector:
        app.kubernetes.io/name: ocular
        control-plane: controller-manager
{{- end }}
