{{- if .Values.certManager.enable }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: ocular
    name: ocular-selfsigned-issuer
    namespace: {{ .Release.Namespace }}
spec:
    selfSigned: {}
{{- end }}
