{{- if .Values.metrics.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ocular-metrics-reader
rules:
    - nonResourceURLs:
        - /metrics
      verbs:
        - get
{{- end }}
