# Copyright (C) 2025 Crash Override, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the FSF, either version 3 of the License, or (at your option) any later version.
# See the LICENSE file in the root of this repository for full license text or
# visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocular.fullname" . }}-api
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ocular.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ocular.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.api.serviceAccount.name }}
      {{ if .Values.images.pullSecrets -}}
      imagePullSecrets:
        {{- toYaml .Values.images.pullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ include "images.api-server" . }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: ASPM_API_PORT
              value: {{ .Values.api.service.port | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port:  {{ .Values.api.service.port }}
              path: /health
          readinessProbe:
            httpGet:
              port: {{ .Values.api.service.port }}
              path: /health
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/ocular
              name: config-vol
      volumes:
        - name: config-vol
          configMap:
            name: ocular-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
