# Copyright (C) 2025 Crash Override, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the FSF, either version 3 of the License, or (at your option) any later version.
# See the LICENSE file in the root of this repository for full license text or
# visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

{{- if .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ocular.fullname" . }}-api
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "batch" ]
    resources: [ "jobs", "cronjobs" ]
    verbs: [ "get", "list", "watch", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "secrets", "configmaps", "services","pods" ]
    verbs: [ "get", "list", "watch", "create", "delete", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ocular.fullname" . }}-api
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
rules:
  - verbs: [ "create", "get" ]
    apiGroups: [ "authentication.k8s.io" , "authorization.k8s.io"]
    resources: [ "tokenreviews", "subjectaccessreviews" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ocular.fullname" . }}-api
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ocular.fullname" . }}-api
subjects:
  - kind: ServiceAccount
    name: {{ .Values.api.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ocular.fullname" . }}-api
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ocular.fullname" . }}-api
subjects:
  - kind: ServiceAccount
    name: {{ .Values.api.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}