{{/* User accounts are service accounts intended for generating tokens for API access. */}}

{{- if .Values.userAccounts.admin.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.userAccounts.admin.name }}
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
  {{- with .Values.userAccounts.admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ocular.fullname" . }}-admin
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ocular.fullname" . }}-admin
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ocular.fullname" . }}-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.userAccounts.admin.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{ if .Values.userAccounts.operator.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.userAccounts.operator.name }}
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
  {{- with .Values.userAccounts.operator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ocular.fullname" . }}-operator
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ocular.fullname" . }}-operator
  labels:
    {{- include "ocular.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ocular.fullname" . }}-operator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.userAccounts.operator.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
