{{- $values := (tpl (.Values | toYaml) $) | fromYaml }}
{{- $values := (tpl ($values | toYaml) $) | fromYaml }}
---
---
apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterDownloader
metadata:
  name: ocular-defaults-gcs
spec:
  container:
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        valueFrom:
          secretKeyRef:
            key: downloader-gcs-credentials
            name: "{{ $values.downloaders.secretName }}"
            optional: true
    image: '{{ $values.downloaders.image.repository }}:{{ $values.downloaders.image.tag }}'
    name: gcs
    resources: {}
