{{- $values := (tpl (.Values | toYaml) $) | fromYaml }}
{{- $values := (tpl ($values | toYaml) $) | fromYaml }}
---
---
apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterDownloader
metadata:
  name: ocular-defaults-git
spec:
  container:
    env:
      - name: GITHUB_APP_PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            key: github-app-private-key
            name: "{{ $values.downloaders.secretName }}"
            optional: true
      - name: GITHUB_APP_ID
        valueFrom:
          secretKeyRef:
            key: github-app-id
            name: "{{ $values.downloaders.secretName }}"
            optional: true
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            key: github-token
            name: "{{ $values.downloaders.secretName }}"
            optional: true
    image: '{{ $values.downloaders.image.repository }}:{{ $values.downloaders.image.tag }}'
    name: git
    resources: {}
    volumeMounts:
      - mountPath: /etc/ocular/gitconfig
        name: git-file-secrets
        readOnly: true
        subPath: gitconfig
  metadataFiles:
    - /mnt/metadata/git.json
  volumes:
    - name: git-file-secrets
      secret:
        optional: true
        secretName: "{{ $values.downloaders.secretName }}"
