{{- $values := (tpl (.Values | toYaml) $) | fromYaml }}
{{- $values := (tpl ($values | toYaml) $) | fromYaml }}
---
---
apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterDownloader
metadata:
  name: ocular-defaults-npm
spec:
  container:
    image: '{{ $values.downloaders.image.repository }}:{{ $values.downloaders.image.tag }}'
    name: npm
    resources: {}
