---
apiVersion: ocular.crashoverride.run/v1beta1
kind: Downloader
metadata:
  name: ocular-defaults-gcs
spec:
  container:
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        valueFrom:
          secretKeyRef:
            key: downloader-gcs-credentials
            name: downloaders-secrets
            optional: true
    image: '{{ .Values.downloaders.image.repository }}:{{ .Values.downloaders.image.tag }}'
    name: gcs
    resources: {}
status: {}
